/**
 * Anti-drift guards: this engine must never claim more than the shared contract grants, and the
 * artefacts inlined at build time must match the contracts they were generated from.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { RUN_EVENT_TYPES } from "../dist/events/index.js";
import { contract, contractActs, introducingAct } from "../dist/blueprint/contract.js";
import { EMBEDDED_ACTS, NOT_PORTABLE, embeddedCapabilities } from "../dist/blueprint/capabilities.js";
import { ACTIONS_SHA256, ENGINE_VERSION, SCHEMA_SHA256 } from "../dist/generated/schema-meta.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const CONTRACTS = resolve(HERE, "..", "..", "..", "contracts");

const readContract = (name) => readFileSync(join(CONTRACTS, name), "utf8");
const sha256 = (text) => createHash("sha256").update(text, "utf8").digest("hex");

test("the run event enumeration covers exactly contracts/events.schema.json", () => {
  const schema = JSON.parse(readContract("events.schema.json"));
  assert.deepEqual([...RUN_EVENT_TYPES].sort(), [...schema.properties.type.enum].sort());
});

test("the inlined artefacts are not stale", () => {
  // They are regenerated by `npm run build`, so a mismatch means someone edited a contract and
  // ran the tests against an older build.
  assert.equal(SCHEMA_SHA256, sha256(readContract("blueprint.schema.json")));
  assert.equal(ACTIONS_SHA256, sha256(readContract("actions.json")));
});

test("the engine announces its own package version", () => {
  // A manifest constrains delivery with `min_engine` (milestone 3-F): a constant that drifted from
  // the published version would let a device accept a Blueprint written for an engine it has not
  // got — the exact cross-update the constraint exists to prevent.
  const { version } = JSON.parse(readFileSync(join(HERE, "..", "package.json"), "utf8"));
  assert.equal(ENGINE_VERSION, version);
});

test("the inlined action contract matches contracts/actions.json", () => {
  assert.deepEqual(contract, JSON.parse(readContract("actions.json")));
});

test("the embedded capability table is a strict subset of the shared contract", () => {
  // The invariant of the whole phase: a Blueprint this engine accepts is always accepted by the
  // Python engine. Never the other way round.
  for (const act of EMBEDDED_ACTS) {
    const shared = new Set(contract.act_capabilities[act]);
    for (const action of embeddedCapabilities(act)) {
      assert.ok(shared.has(action), `${act}: '${action}' is not granted by the shared contract`);
    }
    assert.ok(
      embeddedCapabilities(act).size < shared.size,
      `${act}: the embedded table must be a *strict* subset`,
    );
  }
});

test("every embedded act is declared by the shared contract", () => {
  for (const act of EMBEDDED_ACTS) assert.ok(contractActs().includes(act));
});

test("every non-portable action is one the shared contract actually grants", () => {
  // A stale entry here would silently stop rejecting anything, or reject with the wrong motif.
  for (const action of Object.keys(NOT_PORTABLE)) {
    const granted = EMBEDDED_ACTS.some((act) => contract.act_capabilities[act].includes(action));
    assert.ok(granted, `'${action}' is listed as non-portable but no embedded act grants it`);
    assert.ok(
      !EMBEDDED_ACTS.some((act) => embeddedCapabilities(act).has(action)),
      `'${action}' is listed as non-portable yet the engine claims to run it`,
    );
  }
});

test("introducingAct derives the escalation origin from the capability table", () => {
  assert.equal(introducingAct("http.request"), "vector");
  assert.equal(introducingAct("click"), "continuum");
  assert.equal(introducingAct("read"), "oracle");
  assert.equal(introducingAct("teleport"), undefined);
});
