/**
 * Build step: turn the language-agnostic contracts into ordinary JavaScript modules.
 *
 * The embedded engine runs on Hermes, which supports neither `eval` nor `new Function`. A
 * general-purpose JSON Schema validator builds its validation functions exactly that way, so the
 * compilation happens **here**, at build time: Ajv emits standalone source, and the runtime merely
 * calls it. Same reason the contracts themselves are inlined — a phone has no repository checkout.
 *
 * Outputs, all under `src/generated/` (git-ignored, regenerated by `npm run build`):
 *   - blueprint-validator.ts  the precompiled JSON Schema validator
 *   - actions-contract.ts     contracts/actions.json as a typed constant
 *   - schema-meta.ts          digests of both contracts, so a stale artifact is detectable
 *
 * See docs/embedded.md.
 */

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE = resolve(HERE, "..");
const CONTRACTS = resolve(PACKAGE, "..", "..", "contracts");
const OUT_DIR = join(PACKAGE, "src", "generated");

const BANNER = (source) =>
  `/* GENERATED FILE - do not edit.\n` +
  ` * Produced by sdks/engine/scripts/compile-schema.mjs from contracts/${source}.\n` +
  ` * Regenerate with \`npm run build\` (workspace @aetherius/engine).\n` +
  ` */\n`;

/**
 * Ajv's standalone output pulls a few helpers from its own runtime. Left as-is they would be
 * `require()` calls inside an ES module — unloadable — and would drag Ajv into the shipped app for
 * a handful of lines. We inline them instead, so the generated module is fully self-contained and
 * Ajv stays a build-time dependency. Any helper not listed here fails the build loudly rather than
 * emitting a module that breaks at runtime on a device.
 */
const RUNTIME_HELPERS = {
  // https://github.com/ajv-validator/ajv/blob/master/lib/runtime/ucs2length.ts
  "ajv/dist/runtime/ucs2length": `(function ucs2length(str) {
  const len = str.length;
  let length = 0;
  let pos = 0;
  let value;
  while (pos < len) {
    length++;
    value = str.charCodeAt(pos++);
    if (value >= 0xd800 && value <= 0xdbff && pos < len) {
      value = str.charCodeAt(pos);
      if ((value & 0xfc00) === 0xdc00) pos++;
    }
  }
  return length;
})`,
};

function inlineRuntimeHelpers(source) {
  const out = source.replace(/require\("([^"]+)"\)(?:\.default)?/g, (_match, moduleName) => {
    const inlined = RUNTIME_HELPERS[moduleName];
    if (!inlined) {
      throw new Error(
        `Unsupported Ajv runtime helper "${moduleName}": add its source to RUNTIME_HELPERS in ` +
          `scripts/compile-schema.mjs. Leaving it as a require() would break the module on device.`,
      );
    }
    return inlined;
  });
  // Nothing may reach the device that resolves code at runtime.
  if (/\beval\s*\(|new\s+Function\s*\(/.test(out)) {
    throw new Error("Generated validator contains eval/new Function; refusing to emit it.");
  }
  return out;
}

function sha256(text) {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

function readContract(name) {
  const text = readFileSync(join(CONTRACTS, name), "utf8");
  return { text, data: JSON.parse(text), sha256: sha256(text) };
}

function emitValidator(schema) {
  // strictRequired is off: `anyOf: [{required: [steps]}, {required: [goal]}]` is a legitimate
  // idiom that Ajv's strict mode would otherwise reject. Every other strict check stays on.
  const ajv = new Ajv2020({
    code: { source: true, esm: true, lines: true },
    allErrors: true,
    strict: true,
    strictRequired: false,
  });
  const source = standaloneCode(ajv, ajv.compile(schema));
  return `// @ts-nocheck\n${BANNER("blueprint.schema.json")}${inlineRuntimeHelpers(source)}`;
}

function emitActionsContract(contract) {
  return (
    `${BANNER("actions.json")}` +
    `import type { ActionsContract } from "../blueprint/contract.js";\n\n` +
    `export const ACTIONS_CONTRACT: ActionsContract = ${JSON.stringify(contract, null, 2)};\n`
  );
}

function emitMeta(schemaDigest, actionsDigest) {
  return (
    `${BANNER("blueprint.schema.json + actions.json")}` +
    `/** SHA-256 of contracts/blueprint.schema.json at the time the validator was compiled. */\n` +
    `export const SCHEMA_SHA256 = "${schemaDigest}";\n\n` +
    `/** SHA-256 of contracts/actions.json at the time the contract was inlined. */\n` +
    `export const ACTIONS_SHA256 = "${actionsDigest}";\n`
  );
}

const schema = readContract("blueprint.schema.json");
const actions = readContract("actions.json");

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(join(OUT_DIR, "blueprint-validator.ts"), emitValidator(schema.data), "utf8");
writeFileSync(join(OUT_DIR, "actions-contract.ts"), emitActionsContract(actions.data), "utf8");
writeFileSync(join(OUT_DIR, "schema-meta.ts"), emitMeta(schema.sha256, actions.sha256), "utf8");

console.log(`Generated ${OUT_DIR} from ${CONTRACTS}`);
