/**
 * Build step: assemble the injected agent into one injectable string.
 *
 * The agent is the half of Act II that runs *inside* the page. It is written as ordinary TypeScript
 * modules — locators, auto-waiting, operations, DOM reads are four distinct jobs and each deserves
 * its own file — but what a WebView accepts is a single source string. Assembling it is therefore a
 * build step, exactly as the JSON Schema validator is on the engine side: esbuild is a build
 * dependency, never a runtime one, and what ships is ordinary JavaScript.
 *
 * Outputs, under `src/generated/` (git-ignored, regenerated by `npm run build`):
 *   - agent-source.ts   the bundle as a constant, plus the digest of the sources it came from
 *
 * The digest exists so a stale artefact is detectable: `test/agent-build.test.js` recomputes it
 * from the files on disk. A driver talking to an agent built from older sources would fail in ways
 * that look like a browser problem, which is the worst kind of bug to chase.
 */

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE = resolve(HERE, "..");
const AGENT_DIR = join(PACKAGE, "src", "webview", "agent");
const ENTRY = join(AGENT_DIR, "index.ts");
const OUT_DIR = join(PACKAGE, "src", "generated");

/** Every file the bundle is built from, sorted, so the digest is stable across machines. */
function sourceFiles() {
  const found = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) walk(path);
      else if (entry.name.endsWith(".ts")) found.push(path);
    }
  };
  walk(AGENT_DIR);
  // The protocol is shared with the driver and lives outside the agent directory; a change to the
  // envelope must invalidate the bundle just as much as a change to an operation.
  found.push(join(PACKAGE, "src", "webview", "protocol.ts"));
  return found.sort();
}

function digest(files) {
  const hash = createHash("sha256");
  for (const path of files) {
    hash.update(relative(PACKAGE, path).split("\\").join("/"), "utf8");
    hash.update("\0", "utf8");
    hash.update(readFileSync(path, "utf8"), "utf8");
    hash.update("\0", "utf8");
  }
  return hash.digest("hex");
}

const files = sourceFiles();

const bundled = await build({
  entryPoints: [ENTRY],
  bundle: true,
  write: false,
  // An IIFE, because the page has no module loader and the agent must leave exactly one global
  // behind. ES2017 is the floor of the WebViews this package supports (iOS 13 / Chrome 60+); the
  // agent runs in the page, not in Hermes, so it is not bound by the engine's constraints.
  format: "iife",
  platform: "browser",
  target: "es2017",
  // Kept readable on purpose: when a real portal misbehaves, the only thing between the developer
  // and the truth is this source, read in a WebView inspector. A few kilobytes injected per
  // navigation is a price worth paying for that.
  minify: false,
  legalComments: "none",
});

const [output] = bundled.outputFiles;
if (output === undefined) throw new Error("esbuild produced no output for the injected agent");

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(
  join(OUT_DIR, "agent-source.ts"),
  `/* GENERATED FILE - do not edit.\n` +
    ` * Produced by sdks/react-native/scripts/build-agent.mjs from src/webview/agent/.\n` +
    ` * Regenerate with \`npm run build\` (workspace @aetherius/react-native).\n` +
    ` */\n\n` +
    `/** The injected agent, as one self-contained IIFE. */\n` +
    `export const AGENT_SOURCE = ${JSON.stringify(output.text)};\n\n` +
    `/** Digest of the sources the bundle was built from; a stale artefact is detectable. */\n` +
    `export const AGENT_SHA256 = ${JSON.stringify(digest(files))};\n`,
  "utf8",
);

console.log(
  `agent bundled: ${files.length} sources -> ${output.text.length} bytes ` +
    `(src/generated/agent-source.ts)`,
);
